site_name: Deep Log Inspection
repo_url: https://github.com/martel-innovate/deep-log-inspection.git
site_description: Deep Log Inspection documentation
docs_dir: 'doc'
theme: readthedocs
pages:
    - Home: 'index.md'
    - Quick Start: 'quickstart.md'
    - System Architecture: 'architecture.md'
    - User Manual:
        - 'Introduction': 'user/introduction.md'
        - 'Quick Start': 'user/quickstart.md'
        - 'Advanced usage':
            - 'Introduction': 'user/advanced.md'
            - 'Elasticsearch API queries': 'user/elasticsearch.md'
            - 'Searching logs in Kibana': 'user/kibana-logs.md'
            - 'Custom visualizations in Kibana': 'user/kibana-visual.md'
    - Installation & Administration Manual:
        - 'Deep Log Inspection':
            - 'Introduction': 'install/introduction.md'
            - 'Installing & Deploying': 'install/install.md'
            - 'Configuring the Monasca Log API': 'install/monasca-log-api.md'
            - 'Configuring Kafka': 'install/kafka.md'
        - 'Monasca Log Agent':
            - 'Installing & Deploying': 'install/monasca-log-agent.md'
