site_name: Deep Log Inspection - readthedocs
site_url: http://deep-log-inspection.readthedocs.io
repo_url: https://github.com/martel-innovate/deep-log-monasca-elk.git
site_description: Deep Log Inspection documentation
docs_dir: .
theme: readthedocs
pages:
    - Home: 'doc/TOC.md'
    - Architecture: 'doc/architecture.md'
    - User Manual:
        - Introduction: 'doc/user/1-intro.md'
        - Quick start: 'doc/user/2-quickstart.md'
        - Advanced usage:
            - Introduction: 'doc/user/3-advanced.md'
            - Elasticsearch API queries: 'doc/user/4-elasticsearch.md'
            - Searching logs in Kibana: 'doc/user/5-kibana-logs.md'
            - Custom visualizations in Kibana: 'doc/user/6-kibana-visual.md'
    - Installation & Administration Manual:
        - Deep Log Inspection server:
            - Introduction: 'doc/install/1-intro.md'
            - Installing & Deploying: 'doc/install/2-install.md'
            - Configuring the Monasca Log API: 'doc/install/3-monasca.md'
            - Configuring Kafka: 'doc/install/4-kafka.md'
        - Monasca Log Agent:
            - Installing & Deploying: 'doc/install/5-log-agent.md'
