site_name: Deep Log Inspection - readthedocs
site_url: http://deep-log-inspection.readthedocs.io
repo_url: https://github.com/martel-innovate/deep-log-monasca-elk.git
site_description: Deep Log Inspection documentation
docs_dir: .
theme: readthedocs
pages:
    - Home: 'TOC.md'
