#!/bin/bash
# cron job for SSL certificate renewal
docker run --rm -p 443:443 --name certbot \
    -v "/etc/letsencrypt:/etc/letsencrypt" \
    -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
    -v "/var/log/letsencrypt:/var/log/letsencrypt" \
    certbot/certbot renew \
    --prehook "docker service rm deeplog_monasca-log-api" \
    --post-hook "docker stack deploy -c docker-compose.yml deeplog"
