#### Entrypoints + Let's Encrypt
## please refer to:
# https://docs.traefik.io/configuration/entrypoints/
# https://docs.traefik.io/configuration/acme/

[entryPoints]
    [entryPoints.http]
    address = ":80"
        ## uncomment to redirect http to https
        # [entryPoints.http.redirect]
        # entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        ## uncomment to set TLS certificate
        # [entryPoints.https.tls]
        #     [acme]
        #     email = "address here"
        #     storage = "path to letsencrypt folder"
        #     entryPoint = "https"
        #     [[acme.domains]]
        #     main = "name of manager node"
        #     sans = ["alternative name for elasticsearch","alternative name for kibana"]
