version: '2'
services:

    zookeeper:
        image: zookeeper:3.3

    kafka:
        image: monasca/kafka:0.9.0.1-2.11
        environment:
            ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
            KAFKA_AUTO_CREATE_TOPICS: "false"
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            KAFKA_CREATE_TOPICS: "\
                monasca-log:16:1,logstash-log:16:1,\
                kafka-health:12:1"
        depends_on:
            - zookeeper
        restart: on-failure

    monasca-log-api:
        build: monasca-log-api/
        image: monasca-log-api
        volumes:
            - ./monasca-log-api/config:/etc/monasca
        depends_on:
            - kafka
        ports:
            - "8090:8090"
        restart: on-failure

    logstash-transformer:
        build: logstash-transformer/
        image: monasca-logstash-transformer
        volumes:
            - ./logstash-transformer/config/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./logstash-transformer/pipeline:/usr/share/logstash/pipeline
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        depends_on:
          - kafka

    logstash-persister:
        build: logstash-persister/
        image: monasca-logstash-persister
        volumes:
            - ./logstash-persister/config/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./logstash-persister/pipeline:/usr/share/logstash/pipeline
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        depends_on:
            - kafka
            - elasticsearch

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - esdata1:/usr/share/elasticsearch/data
            - eslogs1:/usr/share/elasticsearch/logs
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          ES_JAVA_OPTS: "-Xmx256m -Xms256m"

    kibana:
        image: docker.elastic.co/kibana/kibana:5.4.0
        volumes:
          - ./kibana/config/:/usr/share/kibana/config
        ports:
          - "5601:5601"
        depends_on:
          - elasticsearch

volumes:
    esdata1:
        external:
            name: monascadocker_esdata1
    eslogs1:
        driver: local
