version: '3'
services:

    zookeeper:
        image: zookeeper:3.3
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure

    kafka:
        image: monasca/kafka:0.9.0.1-2.11
        environment:
            ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
            KAFKA_AUTO_CREATE_TOPICS: "false"
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            KAFKA_CREATE_TOPICS: "\
                monasca-log:16:1,logstash-log:16:1,\
                kafka-health:12:1"
        depends_on:
            - zookeeper
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure

    monasca-log-api:
        image: martel/monasca-log-api
        volumes:
            - ./monasca-log-api/config:/etc/monasca
        depends_on:
            - kafka
        ports:
            - "8090:8090"
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure

    log-transformer:
        image: martel/log-transformer
        volumes:
            - ./log-transformer/config/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./log-transformer/pipeline:/usr/share/logstash/pipeline
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        depends_on:
          - kafka
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure

    log-persister:
        image: martel/log-persister
        volumes:
            - ./log-persister/config/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./log-persister/pipeline:/usr/share/logstash/pipeline
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        depends_on:
            - kafka
            - elasticsearch
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile: 1048576
            nproc: -1
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - esdata:/usr/share/elasticsearch/data
            - eslogs:/usr/share/elasticsearch/logs
        ports:
          - "9200:9200"
          - "9300:9300"
        restart: on-failure
        deploy:
            resources:
                limits:
                    memory: 1g
            restart_policy:
                condition: on-failure

    kibana:
        image: docker.elastic.co/kibana/kibana:5.4.0
        volumes:
          - ./kibana/config/:/usr/share/kibana/config
        ports:
          - "5601:5601"
        depends_on:
          - elasticsearch
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure

volumes:
    esdata:
        driver: local
    eslogs:
        driver: local
