version: '3.3'
services:

    mysql:
        image: mysql:5.5
        environment:
            MYSQL_ROOT_PASSWORD: secretmysql
        networks:
            - backend
        deploy:
            labels:
                - "traefik.enable=false"
            mode: replicated
            replicas: 1
            placement:
                constraints:
                  - node.hostname == deeplogmanager
            restart_policy:
                condition: on-failure

    mysql-init:
        image: monasca/mysql-init:1.0.0
        environment:
            MYSQL_INIT_DISABLE_REMOTE_ROOT: "true"
            MYSQL_INIT_RANDOM_PASSWORD: "true"
        networks:
            - backend
        deploy:
            labels:
                - "traefik.enable=false"
            mode: replicated
            replicas: 1
            placement:
                constraints:
                  - node.hostname == deeplogmanager

    keystone:
        image: monasca/keystone:1.0.6
        environment:
            KEYSTONE_HOST: keystone
            KEYSTONE_PASSWORD: secretadmin
            KEYSTONE_DATABASE_BACKEND: mysql
            KEYSTONE_MYSQL_HOST: mysql
            KEYSTONE_MYSQL_USER: keystone
            KEYSTONE_MYSQL_PASSWORD: keystone
            KEYSTONE_MYSQL_DATABASE: keystone
        ports:
            - "5000:5000"
            - "35357:35357"
        networks:
            - backend
        depends_on:
            - mysql
        deploy:
            labels:
                - "traefik.enable=false"
            mode: replicated
            replicas: 1
            placement:
                constraints:
                  - node.hostname == deeplogmanager
            restart_policy:
                condition: on-failure
        configs:
            - source: keystone_config
              target: /preload.yml

networks:
    backend:
        external: true

configs:
    keystone_config:
        file: ./keystone/preload.yml
